language: csharp
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono: 5.4.1
dotnet: 2.0.0
before_install:
  - nvm install 8.0.0
  - nvm use 8.0.0
  - cd Unosquare.LedEmotion.Controller
  - npm install
  - cd ..
script:
  - msbuild /t:restore
  - msbuild  
  - npm install -g eslint
  - eslint ./AppClient/*.js ./AppClient/*.jsx


