version: '0.10.{build}'
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
before_build:
- ps: Install-Product node 8
- cd  Unosquare.LedEmotion.Controller
- npm install
build_script:
- dotnet restore
- dotnet build  -c %CONFIGURATION%
